/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as CandidatePortalRouteImport } from './routes/candidate-portal'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as EmployerServicesRouteImport } from './routes/employer-services'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as VisaAttestationServicesRouteImport } from './routes/visa-attestation-services'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DestinationsGulfGccRouteImport } from './routes/destinations.gulf-gcc'
import { Route as DestinationsSchengenEuropeRouteImport } from './routes/destinations.schengen-europe'
import { Route as DestinationsUsaVisaRouteImport } from './routes/destinations.usa-visa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatePortalRoute = CandidatePortalRouteImport.update({
  id: '/candidate-portal',
  path: '/candidate-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerServicesRoute = EmployerServicesRouteImport.update({
  id: '/employer-services',
  path: '/employer-services',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaAttestationServicesRoute = VisaAttestationServicesRouteImport.update({
  id: '/visa-attestation-services',
  path: '/visa-attestation-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsGulfGccRoute = DestinationsGulfGccRouteImport.update({
  id: '/destinations/gulf-gcc',
  path: '/destinations/gulf-gcc',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSchengenEuropeRoute =
  DestinationsSchengenEuropeRouteImport.update({
    id: '/destinations/schengen-europe',
    path: '/destinations/schengen-europe',
    getParentRoute: () => rootRouteImport,
  } as any)
const DestinationsUsaVisaRoute = DestinationsUsaVisaRouteImport.update({
  id: '/destinations/usa-visa',
  path: '/destinations/usa-visa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/candidate-portal': typeof CandidatePortalRoute
  '/contact-us': typeof ContactUsRoute
  '/employer-services': typeof EmployerServicesRoute
  '/industries': typeof IndustriesRoute
  '/unlock': typeof UnlockRoute
  '/visa-attestation-services': typeof VisaAttestationServicesRoute
  '/api/chat': typeof ApiChatRoute
  '/destinations/gulf-gcc': typeof DestinationsGulfGccRoute
  '/destinations/schengen-europe': typeof DestinationsSchengenEuropeRoute
  '/destinations/usa-visa': typeof DestinationsUsaVisaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/candidate-portal': typeof CandidatePortalRoute
  '/contact-us': typeof ContactUsRoute
  '/employer-services': typeof EmployerServicesRoute
  '/industries': typeof IndustriesRoute
  '/unlock': typeof UnlockRoute
  '/visa-attestation-services': typeof VisaAttestationServicesRoute
  '/api/chat': typeof ApiChatRoute
  '/destinations/gulf-gcc': typeof DestinationsGulfGccRoute
  '/destinations/schengen-europe': typeof DestinationsSchengenEuropeRoute
  '/destinations/usa-visa': typeof DestinationsUsaVisaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/candidate-portal': typeof CandidatePortalRoute
  '/contact-us': typeof ContactUsRoute
  '/employer-services': typeof EmployerServicesRoute
  '/industries': typeof IndustriesRoute
  '/unlock': typeof UnlockRoute
  '/visa-attestation-services': typeof VisaAttestationServicesRoute
  '/api/chat': typeof ApiChatRoute
  '/destinations/gulf-gcc': typeof DestinationsGulfGccRoute
  '/destinations/schengen-europe': typeof DestinationsSchengenEuropeRoute
  '/destinations/usa-visa': typeof DestinationsUsaVisaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/candidate-portal'
    | '/contact-us'
    | '/employer-services'
    | '/industries'
    | '/unlock'
    | '/visa-attestation-services'
    | '/api/chat'
    | '/destinations/gulf-gcc'
    | '/destinations/schengen-europe'
    | '/destinations/usa-visa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/candidate-portal'
    | '/contact-us'
    | '/employer-services'
    | '/industries'
    | '/unlock'
    | '/visa-attestation-services'
    | '/api/chat'
    | '/destinations/gulf-gcc'
    | '/destinations/schengen-europe'
    | '/destinations/usa-visa'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/candidate-portal'
    | '/contact-us'
    | '/employer-services'
    | '/industries'
    | '/unlock'
    | '/visa-attestation-services'
    | '/api/chat'
    | '/destinations/gulf-gcc'
    | '/destinations/schengen-europe'
    | '/destinations/usa-visa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  CandidatePortalRoute: typeof CandidatePortalRoute
  ContactUsRoute: typeof ContactUsRoute
  EmployerServicesRoute: typeof EmployerServicesRoute
  IndustriesRoute: typeof IndustriesRoute
  UnlockRoute: typeof UnlockRoute
  VisaAttestationServicesRoute: typeof VisaAttestationServicesRoute
  ApiChatRoute: typeof ApiChatRoute
  DestinationsGulfGccRoute: typeof DestinationsGulfGccRoute
  DestinationsSchengenEuropeRoute: typeof DestinationsSchengenEuropeRoute
  DestinationsUsaVisaRoute: typeof DestinationsUsaVisaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate-portal': {
      id: '/candidate-portal'
      path: '/candidate-portal'
      fullPath: '/candidate-portal'
      preLoaderRoute: typeof CandidatePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer-services': {
      id: '/employer-services'
      path: '/employer-services'
      fullPath: '/employer-services'
      preLoaderRoute: typeof EmployerServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visa-attestation-services': {
      id: '/visa-attestation-services'
      path: '/visa-attestation-services'
      fullPath: '/visa-attestation-services'
      preLoaderRoute: typeof VisaAttestationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/gulf-gcc': {
      id: '/destinations/gulf-gcc'
      path: '/destinations/gulf-gcc'
      fullPath: '/destinations/gulf-gcc'
      preLoaderRoute: typeof DestinationsGulfGccRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/schengen-europe': {
      id: '/destinations/schengen-europe'
      path: '/destinations/schengen-europe'
      fullPath: '/destinations/schengen-europe'
      preLoaderRoute: typeof DestinationsSchengenEuropeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/usa-visa': {
      id: '/destinations/usa-visa'
      path: '/destinations/usa-visa'
      fullPath: '/destinations/usa-visa'
      preLoaderRoute: typeof DestinationsUsaVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  CandidatePortalRoute: CandidatePortalRoute,
  ContactUsRoute: ContactUsRoute,
  EmployerServicesRoute: EmployerServicesRoute,
  IndustriesRoute: IndustriesRoute,
  UnlockRoute: UnlockRoute,
  VisaAttestationServicesRoute: VisaAttestationServicesRoute,
  ApiChatRoute: ApiChatRoute,
  DestinationsGulfGccRoute: DestinationsGulfGccRoute,
  DestinationsSchengenEuropeRoute: DestinationsSchengenEuropeRoute,
  DestinationsUsaVisaRoute: DestinationsUsaVisaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
